version: '2'
services:
    innapcitas-app:
        image: innapcitas
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://innapcitas-postgresql:5432/innapcitas
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    innapcitas-postgresql:
        extends:
            file: postgresql.yml
            service: innapcitas-postgresql
